Restructured repo and brought tf examples
corelight/corelight-cloud pull request #3
Opened 2024-10-25 20:12 UTC by retr0h

2024-10-25 20:15 UTC, retr0h commented
May not be 100% exact but I believe this structure is workable.

2024-11-06 20:02 UTC, thathaneydude requested changes
A couple minor things but I like it!

2024-11-06 20:02 UTC, thathaneydude commented on README.md
> +**Terraform-based** and **cloud-native IaC solutions**, allowing users to
```suggestion
**Terraform-based** and **cloud-native IaC solutions**, allowing you to
```

2024-11-06 20:02 UTC, thathaneydude commented on terraform/aws-cloud-enrichment/README.md
> +on **GCP**.
```suggestion
on **AWS**.
```

2024-11-06 20:02 UTC, thathaneydude commented on terraform/azure-cloud-enrichment/README.md
> +on **GCP**.
```suggestion
on **Azure**.
```

2024-11-06 20:15 UTC, thathaneydude approved these changes

2024-11-06 20:16 UTC, merged